/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.phuong.tester.automation.gui.dialog;

import java.awt.Frame;
import vn.phuong.tester.automation.skill.panel.SimpleTestPanel;
import vn.phuong.tester.automation.skill.panel.SelectionPanel;
import vn.phuong.tester.automation.skill.panel.OpenSkillPanel;
import vn.phuong.tester.automation.skill.panel.VerifyPanel;
import vn.phuong.tester.automation.skill.panel.InputPanel;
import vn.phuong.tester.automation.skill.panel.ClickPanel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JTable;
import vn.phuong.tester.automation.constraint.SkillType;

import vn.phuong.tester.automation.gui.model.SkillModel;
import vn.phuong.tester.automation.skill.ClickSkill;
import vn.phuong.tester.automation.skill.InputSkill;
import vn.phuong.tester.automation.skill.OpenSkill;
import vn.phuong.tester.automation.skill.SelectionSkill;
import vn.phuong.tester.automation.skill.AbstractTestSkill;
import vn.phuong.tester.automation.skill.VerifySkill;

/**
 *
 * @author ADMIN
 */
public class EditSkillDialog extends javax.swing.JDialog {
 
    private JTable jTable;
    private SimpleTestPanel panel;
    private boolean isCreation;
    private boolean isEdition = true;
    
    private static final String CREATE = "Tạo mới";
    private static final String EDIT = "Lưu thay đổi";
    
    public EditSkillDialog(Frame parent, boolean modal,boolean isCreation, JTable jTable1) {
        super(parent, modal);
        this.isCreation = isCreation;
        this.jTable = jTable1;
        initComponents();
        if(isCreation){
            jButton2.setText(CREATE);
        }
    }

    /**
     * Creates new form EditSkillDialog
     */
    public EditSkillDialog(Frame parent, boolean modal, JTable jTable1) {
        super(parent, modal);
        this.jTable = jTable1;
        initComponents();
        SkillModel model = (SkillModel) jTable.getModel();
        AbstractTestSkill skill = model.getSkill(jTable.getSelectedRow());
        replaceMainPanel(skill);
    }
    
    private void replaceMainPanel(AbstractTestSkill skill){
        GroupLayout layout =  (GroupLayout) getContentPane().getLayout();
          if(skill instanceof OpenSkill){
            panel = new OpenSkillPanel(skill);
        }
        if(skill instanceof SelectionSkill){
            panel = new SelectionPanel(skill);
        }
        if(skill instanceof ClickSkill){
            panel = new ClickPanel(skill);
        }
        if(skill instanceof InputSkill){
            panel = new InputPanel(skill);
        }
        if(skill instanceof VerifySkill){
            panel = new VerifyPanel(skill);
        }
        if(panel != null)
            layout.replace(mainPanel, panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tùy Chỉnh Hành Động");

        jButton1.setText("Hủy thay đổi");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Lưu thay đổi");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel1.setText("Chọn hành động:");

        jComboBox1.setModel(new DefaultComboBoxModel(SkillType.values()));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, 0, 307, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if(isCreation) {
            onCreation();
            isEdition = false;
            return;
        } 
        SkillModel model = (SkillModel) jTable.getModel();
        if(isEdition){
            model.editSkill(jTable.getSelectedRow(), panel.mappingElement());
        } else{
            model.insertSkillAt(jTable.getSelectedRow() + 1, panel.mappingElement());
            if(model.getRowCount() != 1)
                jTable.setRowSelectionInterval(jTable.getSelectedRow()+1, jTable.getSelectedRow()+1);
            isEdition = true;
        }
        jTable.addNotify();
        this.jButton1MouseClicked(evt);
    }//GEN-LAST:event_jButton2MouseClicked

    private void onCreation(){
        SkillType type = (SkillType) jComboBox1.getSelectedItem();
        if(SkillType.OPEN.equals(type)){
            replaceMainPanel(new OpenSkill());
        }
        if(SkillType.INPUT.equals(type)){
            replaceMainPanel(new InputSkill());
        }
        if(SkillType.SELECT.equals(type)){
            replaceMainPanel(new SelectionSkill());
        }
        if(SkillType.CLICK.equals(type)){
            replaceMainPanel(new ClickSkill());
        }
        if(SkillType.VERIFY.equals(type)){
            replaceMainPanel(new VerifySkill());
        }
        jButton2.setText(EDIT);
        isCreation = false;
    }
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
